# Generated by Django 6.0.3 on 2026-04-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_conversation_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('agent_pending', 'Agent en attente'), ('agent_approved', 'Agent approuvé'), ('contract_expiring', 'Contrat expirant'), ('payment_reminder', 'Rappel de paiement'), ('new_message', 'Nouveau message')], max_length=50),
        ),
    ]
