# Generated by Django 6.0.3 on 2026-04-19 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_alter_notification_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message',
            new_name='content',
        ),
    ]
