# Generated by Django 6.0.3 on 2026-04-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_conversation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
