# Generated by Django 6.0.3 on 2026-03-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('owner_name', models.CharField(max_length=200)),
                ('owner_phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('surface', models.DecimalField(decimal_places=2, help_text='Surface en mètres carrés', max_digits=10, verbose_name='Surface (m²)')),
                ('bedrooms', models.IntegerField(default=1, verbose_name='Nombre de chambres')),
                ('bathrooms', models.IntegerField(default=1, verbose_name='Nombre de salles de bain')),
                ('equipements', models.JSONField(blank=True, default=list, help_text='Liste des équipements', null=True, verbose_name='Équipements')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract_type', models.CharField(choices=[('rent', 'Location'), ('sale', 'Vente')], max_length=20)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('unavailable', 'Indisponible')], default='available', max_length=20)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pieces/properties/')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
