# Generated by Django 6.0.3 on 2026-03-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='available_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de disponibilité'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('loué', 'Loué'), ('en travaux', 'En travaux'), ('reservé', 'Réservé'), ('available', 'Disponible'), ('unavailable', 'Indisponible')], default='available', max_length=20),
        ),
    ]
