# Generated by Django 6.0.3 on 2026-04-12 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_available_date_alter_property_status'),
        ('users', '0005_alter_trusteddevice_device_fingerprint_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='equipements',
            new_name='equipments',
        ),
        migrations.AddField(
            model_name='property',
            name='monthly_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_properties', to='users.person'),
        ),
    ]
