# Generated by Django 6.0.3 on 2026-05-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_rename_equipements_property_equipments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
