# Generated by Django 6.0.3 on 2026-03-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Compte approuvé'),
        ),
    ]
