# Generated by Django 6.0.3 on 2026-03-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_person_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='account_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('active', 'Actif'), ('blocked', 'Bloqué')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='activation_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('owner', 'Propriétaire'), ('tenant', 'Locataire')], default='tenant', max_length=20),
        ),
    ]
