# Generated by Django 6.0.3 on 2026-03-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_person_address_alter_person_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trusteddevice',
            name='device_fingerprint',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='trusteddevice',
            unique_together={('user', 'device_fingerprint')},
        ),
    ]
