# Generated by Django 6.0.3 on 2026-05-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_trusteddevice_device_fingerprint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('owner', 'Propriétaire'), ('tenant', 'Locataire'), ('agent', 'Agent'), ('client', 'Client')], default='tenant', max_length=20),
        ),
    ]
